from __future__ import annotations

import atexit
import json
import shutil
import sqlite3
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from hideout.paths import index_dir, pglite_dir


def _jsonb(value: Any) -> Any:
    from psycopg.types.json import Jsonb

    return Jsonb(value)


def as_vector(values: list[float]) -> Any:
    from pgvector import Vector

    return Vector([float(x) for x in values])

LEGACY_DB = "chunks.sqlite"
LEGACY_VEC = "zvec"
LEGACY_META = "meta.json"
LEGACY_NPY = "embeddings.npy"

_manager = None
_conn = None
_atexit_registered = False

MIGRATIONS: list[tuple[int, list[str]]] = [
    (
        1,
        [
            "CREATE EXTENSION IF NOT EXISTS vector",
            """
            CREATE TABLE IF NOT EXISTS chunks (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                chunk_id TEXT UNIQUE NOT NULL,
                file TEXT NOT NULL,
                book TEXT NOT NULL,
                chapter TEXT NOT NULL,
                headings JSONB NOT NULL DEFAULT '[]'::jsonb,
                page INTEGER,
                printed INTEGER,
                text TEXT NOT NULL,
                embedding vector,
                tsv tsvector GENERATED ALWAYS AS (
                    setweight(to_tsvector('simple', coalesce(book, '')), 'A')
                    || setweight(to_tsvector('simple', coalesce(chapter, '')), 'A')
                    || setweight(to_tsvector('simple', coalesce(file, '')), 'B')
                    || setweight(to_tsvector('simple', coalesce(headings::text, '')), 'B')
                    || setweight(to_tsvector('simple', coalesce(text, '')), 'C')
                ) STORED
            )
            """,
            "CREATE INDEX IF NOT EXISTS chunks_book_idx ON chunks (book)",
            "CREATE INDEX IF NOT EXISTS chunks_tsv_idx ON chunks USING GIN (tsv)",
            """
            CREATE TABLE IF NOT EXISTS meta (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
            """,
        ],
    ),
    (
        2,
        [
            "CREATE EXTENSION IF NOT EXISTS pg_textsearch",
            """
            ALTER TABLE chunks ADD COLUMN IF NOT EXISTS search_text TEXT
            GENERATED ALWAYS AS (
                coalesce(book, '') || ' ' ||
                coalesce(chapter, '') || ' ' ||
                coalesce(file, '') || ' ' ||
                coalesce(headings::text, '') || ' ' ||
                coalesce(text, '')
            ) STORED
            """,
            "DROP INDEX IF EXISTS chunks_bm25_idx",
            """
            CREATE INDEX chunks_bm25_idx ON chunks
            USING bm25 (search_text) WITH (text_config='simple')
            """,
        ],
    ),
]


class _SharedConnection:
    """One live psycopg connection. PGlite only allows a single client."""

    def __init__(self, conn: Any) -> None:
        self._conn = conn

    def close(self) -> None:
        return None

    def __enter__(self) -> _SharedConnection:
        return self

    def __exit__(self, *exc: object) -> None:
        return None

    def __getattr__(self, name: str) -> Any:
        return getattr(self._conn, name)


def _require_node() -> None:
    if shutil.which("node") is None or shutil.which("npm") is None:
        raise SystemExit(
            "hideout needs Node.js (node and npm on PATH) for the local Postgres index"
        )


PGLITE = "0.5.8"
PGLITE_SOCKET = "0.2.11"
PGLITE_PGVECTOR = "0.0.9"
PGLITE_PG_TEXTSEARCH = "0.0.10"
RUNTIME = "pglite-0.5-pg_textsearch"


def _package_json() -> str:
    return json.dumps(
        {
            "name": "hideout-pglite",
            "private": True,
            "dependencies": {
                "@electric-sql/pglite": PGLITE,
                "@electric-sql/pglite-socket": PGLITE_SOCKET,
                "@electric-sql/pglite-pgvector": PGLITE_PGVECTOR,
                "@electric-sql/pglite-pg_textsearch": PGLITE_PG_TEXTSEARCH,
            },
        },
        indent=2,
    ) + "\n"


def _manager_js(socket_path: Path) -> str:
    sock = socket_path.as_posix()
    return f"""\
const {{ PGlite }} = require('@electric-sql/pglite');
const {{ PGLiteSocketServer }} = require('@electric-sql/pglite-socket');
const {{ vector }} = require('@electric-sql/pglite-pgvector');
const {{ pg_textsearch }} = require('@electric-sql/pglite-pg_textsearch');
const {{ unlink }} = require('fs/promises');
const {{ existsSync }} = require('fs');

const SOCKET_PATH = {sock!r};

async function cleanup() {{
  if (existsSync(SOCKET_PATH)) {{
    try {{
      await unlink(SOCKET_PATH);
    }} catch (err) {{
    }}
  }}
}}

async function startServer() {{
  try {{
    const db = await PGlite.create({{
      dataDir: './pgdata',
      extensions: {{
        vector,
        pg_textsearch,
      }},
    }});
    await cleanup();
    const server = new PGLiteSocketServer({{
      db,
      path: SOCKET_PATH,
    }});
    await server.start();
    console.log(`Server started on socket ${{SOCKET_PATH}}`);

    const shutdown = async () => {{
      try {{
        await server.stop();
        await db.close();
      }} catch (err) {{
        console.error('Error during shutdown:', err);
      }}
      process.exit(0);
    }};
    process.on('SIGINT', shutdown);
    process.on('SIGTERM', shutdown);
  }} catch (err) {{
    console.error('Failed to start PGlite server:', err);
    process.exit(1);
  }}
}}

startServer();
"""


def _prepare_runtime(work: Path, socket: Path) -> None:
    work.mkdir(parents=True, exist_ok=True)
    (work / "pgdata").mkdir(parents=True, exist_ok=True)
    pkg = _package_json()
    pkg_path = work / "package.json"
    js_path = work / "pglite_manager.js"
    js = _manager_js(socket)
    old_pkg = pkg_path.read_text(encoding="utf-8") if pkg_path.is_file() else ""
    need_npm = old_pkg != pkg or not (work / "node_modules").is_dir()
    if old_pkg != pkg:
        pkg_path.write_text(pkg, encoding="utf-8")
    if not js_path.is_file() or js_path.read_text(encoding="utf-8") != js:
        js_path.write_text(js, encoding="utf-8")
    if need_npm:
        print("installing pglite extensions…", file=sys.stderr)
        subprocess.run(
            ["npm", "install"],
            cwd=work,
            check=True,
            timeout=180,
        )
    _rotate_old_pgdata(work)


def _rotate_old_pgdata(work: Path) -> None:
    marker = work / "runtime.txt"
    current = marker.read_text(encoding="utf-8").strip() if marker.is_file() else ""
    if current == RUNTIME:
        return
    pgdata = work / "pgdata"
    if pgdata.is_dir() and any(pgdata.iterdir()):
        bak = work / f"pgdata.bak-{current or 'legacy'}"
        if bak.exists():
            shutil.rmtree(bak)
        pgdata.rename(bak)
        pgdata.mkdir()
        print(
            f"pglite runtime changed; moved old data to {bak.name}. "
            "the index will rebuild on next search.",
            file=sys.stderr,
        )


def _mark_runtime(work: Path) -> None:
    (work / "runtime.txt").write_text(RUNTIME + "\n", encoding="utf-8")


def _alive() -> bool:
    if _manager is None or _conn is None:
        return False
    proc = getattr(_manager, "process", None)
    return proc is not None and proc.poll() is None


def ensure_db() -> None:
    global _manager, _conn, _atexit_registered
    if _alive():
        return
    stop_db()
    _require_node()

    from pgvector.psycopg import register_vector
    from psycopg.rows import dict_row
    from py_pglite import PGliteConfig, PGliteManager

    work = pglite_dir()
    socket = work / ".s.PGSQL.5432"
    _prepare_runtime(work, socket)
    config = PGliteConfig(
        timeout=90,
        cleanup_on_exit=False,
        log_level="ERROR",
        work_dir=work,
        socket_path=str(socket),
        extensions=["pgvector"],
    )
    print("starting local postgres…", file=sys.stderr)
    manager = PGliteManager(config)
    manager.start()
    _manager = manager
    try:
        raw = _connect_psycopg(config.get_dsn(), dict_row)
        raw.execute("CREATE EXTENSION IF NOT EXISTS vector")
        raw.execute("CREATE EXTENSION IF NOT EXISTS pg_textsearch")
        register_vector(raw)
        _conn = _SharedConnection(raw)
        migrate(_conn)
        _mark_runtime(pglite_dir())
    except Exception:
        stop_db()
        raise
    if not _atexit_registered:
        atexit.register(stop_db)
        _atexit_registered = True


def _connect_psycopg(dsn: str, dict_row: Any) -> Any:
    import psycopg

    last: Exception | None = None
    for attempt in range(8):
        try:
            return psycopg.connect(
                dsn,
                autocommit=True,
                row_factory=dict_row,
                connect_timeout=3,
            )
        except Exception as exc:
            last = exc
            if _manager is not None:
                proc = getattr(_manager, "process", None)
                if proc is not None and proc.poll() is not None:
                    break
            time.sleep(0.25)
    assert last is not None
    raise last


def stop_db() -> None:
    global _manager, _conn
    conn, _conn = _conn, None
    if conn is not None:
        raw = getattr(conn, "_conn", conn)
        try:
            raw.close()
        except Exception:
            pass
    manager, _manager = _manager, None
    if manager is not None:
        try:
            manager.stop()
        except Exception:
            pass


def connect() -> _SharedConnection:
    ensure_db()
    if _conn is None:
        raise SystemExit("no index yet; run: python -m hideout index")
    return _conn


def migrate(conn: Any) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    applied = {
        int(row["version"])
        for row in conn.execute("SELECT version FROM schema_migrations")
    }
    for version, statements in MIGRATIONS:
        if version in applied:
            continue
        for sql in statements:
            conn.execute(sql)
        conn.execute(
            "INSERT INTO schema_migrations (version) VALUES (%s)",
            (version,),
        )
    _import_legacy(conn)


def get_meta(key: str) -> str | None:
    conn = connect()
    row = conn.execute("SELECT value FROM meta WHERE key = %s", (key,)).fetchone()
    if row is None:
        return None
    return str(row["value"])


def set_meta(key: str, value: str, conn: Any | None = None) -> None:
    db = conn if conn is not None else connect()
    db.execute(
        """
        INSERT INTO meta (key, value) VALUES (%s, %s)
        ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
        """,
        (key, value),
    )


def count_chunks() -> int:
    conn = connect()
    row = conn.execute("SELECT COUNT(*) AS n FROM chunks").fetchone()
    return int(row["n"]) if row else 0


def missing_embeddings() -> int:
    conn = connect()
    row = conn.execute(
        "SELECT COUNT(*) AS n FROM chunks WHERE embedding IS NULL"
    ).fetchone()
    return int(row["n"]) if row else 0


def set_embedding_dim(conn: Any, dim: int) -> None:
    conn.execute(f"ALTER TABLE chunks ALTER COLUMN embedding TYPE vector({int(dim)})")
    set_meta("dim", str(dim), conn)


def reset_chunks(conn: Any) -> None:
    conn.execute("TRUNCATE chunks RESTART IDENTITY")


def try_hnsw(conn: Any) -> None:
    try:
        conn.execute("DROP INDEX IF EXISTS chunks_embedding_idx")
        conn.execute(
            "CREATE INDEX chunks_embedding_idx ON chunks "
            "USING hnsw (embedding vector_cosine_ops)"
        )
    except Exception:
        pass


def try_bm25(conn: Any) -> None:
    conn.execute("DROP INDEX IF EXISTS chunks_bm25_idx")
    conn.execute(
        """
        CREATE INDEX chunks_bm25_idx ON chunks
        USING bm25 (search_text) WITH (text_config='simple')
        """
    )


def _load_zvec(path: Path) -> dict[int, list[float]]:
    import zvec

    coll = zvec.open(
        str(path),
        option=zvec.CollectionOption(read_only=True, enable_mmap=True),
    )
    out: dict[int, list[float]] = {}
    try:
        for doc in coll.iter_docs(include_vector=True):
            try:
                rowid = int(doc.id)
            except (TypeError, ValueError):
                continue
            raw = doc.vector("embedding")
            if raw is None:
                continue
            out[rowid] = [float(x) for x in raw]
    finally:
        coll.close()
    return out


def remove_legacy() -> None:
    root = index_dir()
    for name in (LEGACY_DB, LEGACY_META, LEGACY_NPY):
        path = root / name
        if path.is_file():
            path.unlink()
    vec = root / LEGACY_VEC
    if vec.exists():
        shutil.rmtree(vec, ignore_errors=True)


def _import_legacy(conn: Any) -> None:
    sqlite_path = index_dir() / LEGACY_DB
    vec_dir = index_dir() / LEGACY_VEC
    if not sqlite_path.is_file():
        return
    row = conn.execute("SELECT COUNT(*) AS n FROM chunks").fetchone()
    if row and int(row["n"]):
        return
    if not vec_dir.exists():
        return
    try:
        embeddings = _load_zvec(vec_dir)
    except Exception:
        return
    if not embeddings:
        return

    src = sqlite3.connect(sqlite_path)
    src.row_factory = sqlite3.Row
    try:
        rows = src.execute(
            """
            SELECT rowid, id, file, book, chapter, headings, page, printed, text
            FROM chunks
            ORDER BY rowid
            """
        ).fetchall()
    finally:
        src.close()
    if not rows:
        return
    if any(int(r["rowid"]) not in embeddings for r in rows):
        return

    print("migrating sqlite + zvec index into pglite…", file=sys.stderr)
    dim = len(next(iter(embeddings.values())))
    with conn.transaction():
        for r in rows:
            rowid = int(r["rowid"])
            headings = r["headings"]
            if isinstance(headings, str):
                headings = json.loads(headings)
            conn.execute(
                """
                INSERT INTO chunks (
                    id, chunk_id, file, book, chapter, headings,
                    page, printed, text, embedding
                )
                OVERRIDING SYSTEM VALUE
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    rowid,
                    r["id"],
                    r["file"],
                    r["book"],
                    r["chapter"],
                    _jsonb(headings),
                    r["page"],
                    r["printed"],
                    r["text"],
                    as_vector(embeddings[rowid]),
                ),
            )
        set_embedding_dim(conn, dim)
        conn.execute(
            """
            SELECT setval(
                pg_get_serial_sequence('chunks', 'id'),
                (SELECT COALESCE(MAX(id), 1) FROM chunks)
            )
            """
        )
        meta_path = index_dir() / LEGACY_META
        if meta_path.is_file():
            try:
                data = json.loads(meta_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                data = {}
            if data.get("source_hash"):
                set_meta("source_hash", str(data["source_hash"]), conn)
        set_meta("chunks", str(len(rows)), conn)
        set_meta("vectors", "pgvector", conn)
    try_hnsw(conn)
    try_bm25(conn)
    remove_legacy()
