from __future__ import annotations

import atexit
import json
import re
import shutil
import sqlite3
import sys
from pathlib import Path
from typing import Any

from hideout.paths import index_dir, pglite_dir


def _jsonb(value: Any) -> Any:
    from psycopg.types.json import Jsonb

    return Jsonb(value)


def as_vector(values: list[float]) -> Any:
    from pgvector import Vector

    return Vector([float(x) for x in values])

LEGACY_DB = "chunks.sqlite"
LEGACY_VEC = "zvec"
LEGACY_META = "meta.json"
LEGACY_NPY = "embeddings.npy"

_manager = None
_conn = None
_atexit_registered = False

MIGRATIONS: list[tuple[int, list[str]]] = [
    (
        1,
        [
            "CREATE EXTENSION IF NOT EXISTS vector",
            """
            CREATE TABLE IF NOT EXISTS chunks (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                chunk_id TEXT UNIQUE NOT NULL,
                file TEXT NOT NULL,
                book TEXT NOT NULL,
                chapter TEXT NOT NULL,
                headings JSONB NOT NULL DEFAULT '[]'::jsonb,
                page INTEGER,
                printed INTEGER,
                text TEXT NOT NULL,
                embedding vector,
                tsv tsvector GENERATED ALWAYS AS (
                    setweight(to_tsvector('simple', coalesce(book, '')), 'A')
                    || setweight(to_tsvector('simple', coalesce(chapter, '')), 'A')
                    || setweight(to_tsvector('simple', coalesce(file, '')), 'B')
                    || setweight(to_tsvector('simple', coalesce(headings::text, '')), 'B')
                    || setweight(to_tsvector('simple', coalesce(text, '')), 'C')
                ) STORED
            )
            """,
            "CREATE INDEX IF NOT EXISTS chunks_book_idx ON chunks (book)",
            "CREATE INDEX IF NOT EXISTS chunks_tsv_idx ON chunks USING GIN (tsv)",
            """
            CREATE TABLE IF NOT EXISTS meta (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
            """,
        ],
    ),
]


class _SharedConnection:
    """One live psycopg connection. PGlite only allows a single client."""

    def __init__(self, conn: Any) -> None:
        self._conn = conn

    def close(self) -> None:
        return None

    def __enter__(self) -> _SharedConnection:
        return self

    def __exit__(self, *exc: object) -> None:
        return None

    def __getattr__(self, name: str) -> Any:
        return getattr(self._conn, name)


def _require_node() -> None:
    if shutil.which("node") is None or shutil.which("npm") is None:
        raise SystemExit(
            "hideout needs Node.js (node and npm on PATH) for the local Postgres index"
        )


_js_patched = False


def _patch_manager_js() -> None:
    global _js_patched
    if _js_patched:
        return
    from py_pglite.manager import PGliteManager

    orig = PGliteManager._generate_unix_js_content

    def with_datadir(self, ext_requires_str: str, extensions_obj_str: str) -> str:
        js = orig(self, ext_requires_str, extensions_obj_str)
        patched, n = re.subn(
            r"const db = new PGlite\(\{\s*extensions:",
            "const db = new PGlite({\n  dataDir: './pgdata',\n  extensions:",
            js,
            count=1,
        )
        if n != 1:
            raise RuntimeError("py-pglite JS template changed; cannot enable dataDir")
        return patched

    PGliteManager._generate_unix_js_content = with_datadir  # type: ignore[method-assign]
    _js_patched = True


def _alive() -> bool:
    if _manager is None or _conn is None:
        return False
    proc = getattr(_manager, "process", None)
    return proc is not None and proc.poll() is None


def ensure_db() -> None:
    global _manager, _conn, _atexit_registered
    if _alive():
        return
    stop_db()
    _require_node()

    from pgvector.psycopg import register_vector
    from psycopg.rows import dict_row
    import psycopg
    from py_pglite import PGliteConfig, PGliteManager

    _patch_manager_js()

    work = pglite_dir()
    work.mkdir(parents=True, exist_ok=True)
    (work / "pgdata").mkdir(parents=True, exist_ok=True)
    js = work / "pglite_manager.js"
    if js.is_file() and "dataDir" not in js.read_text(encoding="utf-8"):
        js.unlink()

    socket = work / ".s.PGSQL.5432"
    config = PGliteConfig(
        timeout=90,
        cleanup_on_exit=False,
        log_level="ERROR",
        work_dir=work,
        socket_path=str(socket),
        extensions=["pgvector"],
    )
    print("starting local postgres…", file=sys.stderr)
    manager = PGliteManager(config)
    manager.start()
    _manager = manager
    try:
        raw = psycopg.connect(config.get_dsn(), autocommit=True, row_factory=dict_row)
        raw.execute("CREATE EXTENSION IF NOT EXISTS vector")
        register_vector(raw)
        _conn = _SharedConnection(raw)
        migrate(_conn)
    except Exception:
        stop_db()
        raise
    if not _atexit_registered:
        atexit.register(stop_db)
        _atexit_registered = True


def stop_db() -> None:
    global _manager, _conn
    conn, _conn = _conn, None
    if conn is not None:
        raw = getattr(conn, "_conn", conn)
        try:
            raw.close()
        except Exception:
            pass
    manager, _manager = _manager, None
    if manager is not None:
        try:
            manager.stop()
        except Exception:
            pass


def connect() -> _SharedConnection:
    ensure_db()
    if _conn is None:
        raise SystemExit("no index yet; run: python -m hideout index")
    return _conn


def migrate(conn: Any) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    applied = {
        int(row["version"])
        for row in conn.execute("SELECT version FROM schema_migrations")
    }
    for version, statements in MIGRATIONS:
        if version in applied:
            continue
        for sql in statements:
            conn.execute(sql)
        conn.execute(
            "INSERT INTO schema_migrations (version) VALUES (%s)",
            (version,),
        )
    _import_legacy(conn)


def get_meta(key: str) -> str | None:
    conn = connect()
    row = conn.execute("SELECT value FROM meta WHERE key = %s", (key,)).fetchone()
    if row is None:
        return None
    return str(row["value"])


def set_meta(key: str, value: str, conn: Any | None = None) -> None:
    db = conn if conn is not None else connect()
    db.execute(
        """
        INSERT INTO meta (key, value) VALUES (%s, %s)
        ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
        """,
        (key, value),
    )


def count_chunks() -> int:
    conn = connect()
    row = conn.execute("SELECT COUNT(*) AS n FROM chunks").fetchone()
    return int(row["n"]) if row else 0


def missing_embeddings() -> int:
    conn = connect()
    row = conn.execute(
        "SELECT COUNT(*) AS n FROM chunks WHERE embedding IS NULL"
    ).fetchone()
    return int(row["n"]) if row else 0


def set_embedding_dim(conn: Any, dim: int) -> None:
    conn.execute(f"ALTER TABLE chunks ALTER COLUMN embedding TYPE vector({int(dim)})")
    set_meta("dim", str(dim), conn)


def reset_chunks(conn: Any) -> None:
    conn.execute("TRUNCATE chunks RESTART IDENTITY")


def try_hnsw(conn: Any) -> None:
    try:
        conn.execute("DROP INDEX IF EXISTS chunks_embedding_idx")
        conn.execute(
            "CREATE INDEX chunks_embedding_idx ON chunks "
            "USING hnsw (embedding vector_cosine_ops)"
        )
    except Exception:
        pass


def _load_zvec(path: Path) -> dict[int, list[float]]:
    import zvec

    coll = zvec.open(
        str(path),
        option=zvec.CollectionOption(read_only=True, enable_mmap=True),
    )
    out: dict[int, list[float]] = {}
    try:
        for doc in coll.iter_docs(include_vector=True):
            try:
                rowid = int(doc.id)
            except (TypeError, ValueError):
                continue
            raw = doc.vector("embedding")
            if raw is None:
                continue
            out[rowid] = [float(x) for x in raw]
    finally:
        coll.close()
    return out


def remove_legacy() -> None:
    root = index_dir()
    for name in (LEGACY_DB, LEGACY_META, LEGACY_NPY):
        path = root / name
        if path.is_file():
            path.unlink()
    vec = root / LEGACY_VEC
    if vec.exists():
        shutil.rmtree(vec, ignore_errors=True)


def _import_legacy(conn: Any) -> None:
    sqlite_path = index_dir() / LEGACY_DB
    vec_dir = index_dir() / LEGACY_VEC
    if not sqlite_path.is_file():
        return
    row = conn.execute("SELECT COUNT(*) AS n FROM chunks").fetchone()
    if row and int(row["n"]):
        return
    if not vec_dir.exists():
        return
    try:
        embeddings = _load_zvec(vec_dir)
    except Exception:
        return
    if not embeddings:
        return

    src = sqlite3.connect(sqlite_path)
    src.row_factory = sqlite3.Row
    try:
        rows = src.execute(
            """
            SELECT rowid, id, file, book, chapter, headings, page, printed, text
            FROM chunks
            ORDER BY rowid
            """
        ).fetchall()
    finally:
        src.close()
    if not rows:
        return
    if any(int(r["rowid"]) not in embeddings for r in rows):
        return

    print("migrating sqlite + zvec index into pglite…", file=sys.stderr)
    dim = len(next(iter(embeddings.values())))
    with conn.transaction():
        for r in rows:
            rowid = int(r["rowid"])
            headings = r["headings"]
            if isinstance(headings, str):
                headings = json.loads(headings)
            conn.execute(
                """
                INSERT INTO chunks (
                    id, chunk_id, file, book, chapter, headings,
                    page, printed, text, embedding
                )
                OVERRIDING SYSTEM VALUE
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    rowid,
                    r["id"],
                    r["file"],
                    r["book"],
                    r["chapter"],
                    _jsonb(headings),
                    r["page"],
                    r["printed"],
                    r["text"],
                    as_vector(embeddings[rowid]),
                ),
            )
        set_embedding_dim(conn, dim)
        conn.execute(
            """
            SELECT setval(
                pg_get_serial_sequence('chunks', 'id'),
                (SELECT COALESCE(MAX(id), 1) FROM chunks)
            )
            """
        )
        meta_path = index_dir() / LEGACY_META
        if meta_path.is_file():
            try:
                data = json.loads(meta_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                data = {}
            if data.get("source_hash"):
                set_meta("source_hash", str(data["source_hash"]), conn)
        set_meta("chunks", str(len(rows)), conn)
        set_meta("vectors", "pgvector", conn)
    try_hnsw(conn)
    remove_legacy()
