import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PGlite } from "@electric-sql/pglite";
import { pg_textsearch } from "@electric-sql/pglite-pg_textsearch";
import { vector } from "@electric-sql/pglite-pgvector";
import { HideoutError } from "./errors.js";
import { historyPath, indexDir, pgliteDir } from "./paths.js";

export const LEGACY_DB = "chunks.sqlite";
export const LEGACY_VEC = "zvec";
export const LEGACY_META = "meta.json";
export const LEGACY_NPY = "embeddings.npy";

export const RUNTIME = "pglite-0.5-pg_textsearch";

const MIGRATIONS: [number, string[]][] = [
  [
    1,
    [
      "CREATE EXTENSION IF NOT EXISTS vector",
      `
            CREATE TABLE IF NOT EXISTS chunks (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                chunk_id TEXT UNIQUE NOT NULL,
                file TEXT NOT NULL,
                book TEXT NOT NULL,
                chapter TEXT NOT NULL,
                headings JSONB NOT NULL DEFAULT '[]'::jsonb,
                page INTEGER,
                printed INTEGER,
                text TEXT NOT NULL,
                embedding vector,
                tsv tsvector GENERATED ALWAYS AS (
                    setweight(to_tsvector('simple', coalesce(book, '')), 'A')
                    || setweight(to_tsvector('simple', coalesce(chapter, '')), 'A')
                    || setweight(to_tsvector('simple', coalesce(file, '')), 'B')
                    || setweight(to_tsvector('simple', coalesce(headings::text, '')), 'B')
                    || setweight(to_tsvector('simple', coalesce(text, '')), 'C')
                ) STORED
            )
            `,
      "CREATE INDEX IF NOT EXISTS chunks_book_idx ON chunks (book)",
      "CREATE INDEX IF NOT EXISTS chunks_tsv_idx ON chunks USING GIN (tsv)",
      `
            CREATE TABLE IF NOT EXISTS meta (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
            `,
    ],
  ],
  [
    2,
    [
      "CREATE EXTENSION IF NOT EXISTS pg_textsearch",
      `
            ALTER TABLE chunks ADD COLUMN IF NOT EXISTS search_text TEXT
            GENERATED ALWAYS AS (
                coalesce(book, '') || ' ' ||
                coalesce(chapter, '') || ' ' ||
                coalesce(file, '') || ' ' ||
                coalesce(headings::text, '') || ' ' ||
                coalesce(text, '')
            ) STORED
            `,
      "DROP INDEX IF EXISTS chunks_bm25_idx",
      `
            CREATE INDEX chunks_bm25_idx ON chunks
            USING bm25 (search_text) WITH (text_config='simple')
            `,
    ],
  ],
  [
    3,
    [
      `
            CREATE TABLE IF NOT EXISTS prompt_history (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                line TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            `,
    ],
  ],
];

export const HISTORY_LOAD = 50;

let db: PGlite | null = null;
let opening: Promise<PGlite> | null = null;

export function asVector(values: number[]): string {
  return `[${values.map((x) => Number(x)).join(",")}]`;
}

function rotateOldPgdata(work: string): void {
  const marker = join(work, "runtime.txt");
  const current = existsSync(marker) ? readFileSync(marker, "utf8").trim() : "";
  if (current === RUNTIME) return;
  const pgdata = join(work, "pgdata");
  if (existsSync(pgdata)) {
    const bak = join(work, `pgdata.bak-${current || "legacy"}`);
    if (existsSync(bak)) rmSync(bak, { recursive: true, force: true });
    renameSync(pgdata, bak);
    mkdirSync(pgdata, { recursive: true });
    console.error(
      `pglite runtime changed; moved old data to ${`pgdata.bak-${current || "legacy"}`}. ` +
        "the index will rebuild on next search.",
    );
  }
}

function markRuntime(work: string): void {
  writeFileSync(join(work, "runtime.txt"), RUNTIME + "\n", "utf8");
}

async function openDb(): Promise<PGlite> {
  const work = pgliteDir();
  mkdirSync(work, { recursive: true });
  rotateOldPgdata(work);
  const dataDir = join(work, "pgdata");
  mkdirSync(dataDir, { recursive: true });
  const pg = await PGlite.create({
    dataDir,
    extensions: { vector, pg_textsearch },
  });
  await pg.exec("CREATE EXTENSION IF NOT EXISTS vector");
  await pg.exec("CREATE EXTENSION IF NOT EXISTS pg_textsearch");
  await migrate(pg);
  markRuntime(work);
  return pg;
}

export async function ensureDb(): Promise<PGlite> {
  if (db) return db;
  if (opening) return opening;
  opening = openDb()
    .then((pg) => {
      db = pg;
      return pg;
    })
    .finally(() => {
      opening = null;
    });
  return opening;
}

export async function closeDb(): Promise<void> {
  const pg = db;
  db = null;
  opening = null;
  if (!pg) return;
  try {
    await pg.close();
  } catch {
    // already gone
  }
}

export async function connect(): Promise<PGlite> {
  const pg = await ensureDb();
  if (!pg) throw new HideoutError("no index yet; run: hideout index");
  return pg;
}

export async function migrate(pg: PGlite): Promise<void> {
  await pg.exec(`
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        `);
  const applied = new Set(
    (await pg.query<{ version: number }>("SELECT version FROM schema_migrations")).rows.map((r) =>
      Number(r.version),
    ),
  );
  for (const [version, statements] of MIGRATIONS) {
    if (applied.has(version)) continue;
    for (const sql of statements) {
      await pg.exec(sql);
    }
    await pg.query("INSERT INTO schema_migrations (version) VALUES ($1)", [version]);
  }
  await importLegacyHistory(pg);
}

export async function getMeta(key: string): Promise<string | null> {
  const pg = await connect();
  const row = (
    await pg.query<{ value: string }>("SELECT value FROM meta WHERE key = $1", [key])
  ).rows[0];
  return row ? String(row.value) : null;
}

type Queryable = { query: PGlite["query"] };

export async function setMeta(key: string, value: string, pg?: Queryable): Promise<void> {
  const dbh = pg ?? (await connect());
  await dbh.query(
    `
        INSERT INTO meta (key, value) VALUES ($1, $2)
        ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
        `,
    [key, value],
  );
}

export async function countChunks(): Promise<number> {
  const pg = await connect();
  const row = (await pg.query<{ n: number }>("SELECT COUNT(*) AS n FROM chunks")).rows[0];
  return row ? Number(row.n) : 0;
}

export async function missingEmbeddings(): Promise<number> {
  const pg = await connect();
  const row = (
    await pg.query<{ n: number }>("SELECT COUNT(*) AS n FROM chunks WHERE embedding IS NULL")
  ).rows[0];
  return row ? Number(row.n) : 0;
}

export async function setEmbeddingDim(pg: PGlite, dim: number): Promise<void> {
  await pg.exec(`ALTER TABLE chunks ALTER COLUMN embedding TYPE vector(${Math.trunc(dim)})`);
  await setMeta("dim", String(dim), pg);
}

export async function resetChunks(pg: PGlite): Promise<void> {
  await pg.exec("TRUNCATE chunks RESTART IDENTITY");
}

export async function tryHnsw(pg: PGlite): Promise<void> {
  try {
    await pg.exec("DROP INDEX IF EXISTS chunks_embedding_idx");
    await pg.exec(
      "CREATE INDEX chunks_embedding_idx ON chunks USING hnsw (embedding vector_cosine_ops)",
    );
  } catch {
    // HNSW is optional; sequential scan still works
  }
}

export async function tryBm25(pg: PGlite): Promise<void> {
  await pg.exec("DROP INDEX IF EXISTS chunks_bm25_idx");
  await pg.exec(`
            CREATE INDEX chunks_bm25_idx ON chunks
            USING bm25 (search_text) WITH (text_config='simple')
            `);
}

export async function loadPromptHistory(limit = HISTORY_LOAD): Promise<string[]> {
  const pg = await connect();
  const rows = (
    await pg.query<{ line: string }>(
      "SELECT line FROM prompt_history ORDER BY id DESC LIMIT $1",
      [limit],
    )
  ).rows;
  return rows.map((r) => r.line);
}

export async function appendPromptHistory(line: string): Promise<void> {
  const text = line.trim();
  if (!text) return;
  const pg = await connect();
  const last = (
    await pg.query<{ line: string }>("SELECT line FROM prompt_history ORDER BY id DESC LIMIT 1")
  ).rows[0];
  if (last?.line === text) return;
  await pg.query("INSERT INTO prompt_history (line) VALUES ($1)", [text]);
}

function parseHistoryFile(text: string): string[] {
  const out: string[] = [];
  let buf: string[] = [];
  const flush = () => {
    if (buf.length) {
      out.push(buf.join("\n"));
      buf = [];
    }
  };
  for (const line of text.split("\n")) {
    if (line.startsWith("+")) buf.push(line.slice(1));
    else if (line.startsWith("#")) flush();
    else if (line.trim()) {
      flush();
      out.push(line);
    } else flush();
  }
  flush();
  return out.filter(Boolean);
}

async function importLegacyHistory(pg: PGlite): Promise<void> {
  const row = (await pg.query<{ n: number }>("SELECT COUNT(*) AS n FROM prompt_history")).rows[0];
  if (row && Number(row.n)) return;
  const path = historyPath();
  if (!existsSync(path)) return;
  const lines = parseHistoryFile(readFileSync(path, "utf8"));
  if (!lines.length) return;
  for (const line of lines) {
    await pg.query("INSERT INTO prompt_history (line) VALUES ($1)", [line]);
  }
  try {
    rmSync(path);
  } catch {
    // leave the old file if unlink fails
  }
}

export function removeLegacy(): void {
  const root = indexDir();
  for (const name of [LEGACY_DB, LEGACY_META, LEGACY_NPY]) {
    const path = join(root, name);
    if (existsSync(path)) rmSync(path, { force: true });
  }
  const vec = join(root, LEGACY_VEC);
  if (existsSync(vec)) rmSync(vec, { recursive: true, force: true });
}
